repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gthub.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://gitub.com/pycqa/pylint
    rev: 3.1.0
    hooks:
      - id: pylint
        